
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 8092
spring:
  application:
    name: suivie_cours
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/suivie_cours
    username: root
    password: ismail
  jpa:
    hibernate:
      ddl-auto: create-drop

application:
  config:
    students-url: http://localhost:8222/api/v1/students

