
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://students
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: lb://schools
          predicates:
            - Path=/api/v1/schools/**
  config:
    import: optional:configserver:http://localhost:8888
